"""adicionar_usuario_id_em_tarefas

Revision ID: 1f39c7ee1431
Revises: 58eab62b40c7
Create Date: 2026-09-25 16:47:04.940412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f39c7ee1431'
down_revision: Union[str, Sequence[str], None] = '58eab62b40c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefas', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tarefas', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tarefas', type_='foreignkey')
    op.drop_column('tarefas', 'usuario_id')
    # ### end Alembic commands ###
